name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

permissions:
  contents: read

jobs:
  pretest:
    name: Pre-Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run pretest

  browser:
    name: Browser
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test-browser

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build the Package
        run: npm run build-package
